.circleci/config.yml
packages/react-components/components/date-picker/src/range/date-range-picker-presets.jsx
storybook/yarn.lock
tests/jest.config.js
website/yarn.lock
yarn.lock

Fix jest test on ci  ci

---

packages/react-components/components/multi-select/tests/multi-select.test.jsx
packages/react-components/components/search-input/src/remote-search-input.jsx
packages/react-components/components/search-input/tests/remote-search-input.test.jsx
packages/react-components/components/search-input/tests/search-input.test.jsx
packages/react-components/components/search-input/tests/shared.js
storybook/stories/react-components/search-input/play/remote-search-input.play.stories.jsx

Tests remote search input

---

packages/react-components/components/popup/src/popup.jsx

The date pickers were not closing on an outside click after the clear button of the calendar has been clicked.

Fix the date picker components issue when an outside click is done after a clear button click

---

packages/react-components/components/date-picker/stories/date-range-picker.stories.mdx
packages/react-components/components/date-picker/stories/inline-single-date-picker.stories.mdx
packages/react-components/components/date-picker/stories/single-date-picker.stories.mdx
packages/react-components/components/date-picker/tests/chromatic/date-range-picker.chroma.jsx
packages/react-components/components/date-picker/tests/chromatic/inline-single-date-picker.chroma.jsx
packages/react-components/components/date-picker/tests/chromatic/single-date-picker.chroma.jsx
packages/react-components/components/popup/src/popup.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/24
- Added development stories to test how the calendar open over elements with z-index.
- Added chromatic visual regression tests to validate how the calendar open over elements with z-index.

Added stories to test the date pickers over elements with z-index

---

storybook/stories/materials/icons/icons.stories.mdx

Issue:
Added usage tips for icons

Icon doc precisions

---

packages/react-components/components/button/stories/button.stories.mdx
packages/react-components/components/date-picker/stories/date-range-picker/date-range-picker.stories.mdx
packages/react-components/components/date-picker/stories/single-date-picker/single-date-picker.stories.mdx
storybook/stories/introduction/foundation.stories.mdx
storybook/stories/introduction/tachyons.stories.mdx
storybook/stories/materials/colours/brands.stories.mdx
storybook/stories/materials/colours/sharegate.stories.mdx
storybook/stories/materials/layout/spacing.stories.mdx
storybook/stories/semantic-ui/react/dropdown/standard.stories.mdx
storybook/stories/semantic-ui/react/input/input.stories.mdx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/84
- Rewrote the whole Tachyons docs.

New tachyons docs

---

packages/react-components/.eslintrc.js
packages/react-components/components/button/stories/button.stories.mdx
packages/react-components/components/button/stories/hoc-warning.mdx
packages/react-components/components/date-picker/stories/date-range-picker/date-range-picker.stories.mdx
packages/react-components/components/date-picker/stories/inline-single-date-picker/inline-single-date-picker.stories.mdx
packages/react-components/components/date-picker/stories/single-date-picker/single-date-picker.stories.mdx
packages/react-components/components/label/src/label.jsx
packages/react-components/components/label/stories/standard/standard.stories.mdx
packages/react-components/components/label/stories/tag/tag.stories.mdx
packages/react-components/components/label/tests/chromatic/label.chroma.jsx
packages/react-components/components/multi-select/stories/multi-select.stories.mdx
packages/react-components/components/popup/stories/popup.stories.mdx
packages/react-components/components/search-input/stories/remote-search-input/remote-search-input.stories.mdx
packages/react-components/components/search-input/stories/search-input/search-input.stories.mdx
packages/semantic-ui-theme/semantic/src/definitions/elements/label.less
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/button.overrides
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/label.overrides
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/label.variables
storybook/.eslintrc.js
storybook/blocks/react-components/docs/hoc-warning/hoc-warning.jsx
storybook/blocks/react-components/docs/hoc-warning/index.js
storybook/blocks/react-components/docs/hoc-warning/message.mdx
storybook/blocks/react-components/docs/index.js
storybook/blocks/react-components/docs/installation.mdx
storybook/blocks/react-components/docs/npm-packages.jsx
storybook/blocks/semantic-link/semantic-link.jsx
storybook/config/styles/docs.css
storybook/stories/introduction/tachyons.stories.mdx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/126
- Added a `naked` prop to the label component
- Updated SUI theme to support the naked variant
`yarn start-sb`

Add a naked variant to the label component

---

packages/react-components/components/button/stories/button.stories.mdx
packages/react-components/components/button/tests/chromatic/button.chroma.jsx
packages/react-components/components/button/tests/chromatic/components/buttons.jsx
packages/react-components/components/label/src/label.jsx
packages/react-components/components/label/stories/standard/standard.stories.mdx
packages/react-components/components/label/stories/tag/tag.stories.mdx
packages/react-components/components/label/tests/chromatic/label.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/button.overrides
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/button.variables
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/input.variables
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/label.overrides
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/label.variables

Issue:
https://github.com/gsoft-inc/sg-orbit/issues/106
https://github.com/gsoft-inc/sg-orbit/issues/112
https://github.com/gsoft-inc/sg-orbit/issues/113
https://github.com/gsoft-inc/sg-orbit/issues/147
- Unified font-sizes for medium components.
- Added a prop to Label to pass an Icon / this accepts an icon position too.
- Adjust a label padding / margin when it contains a button / icon.

milestones Labels

---

packages/react-components/src/index.js
packages/react-components/tests/exports.test.js
packages/tachyons/docs/plugins/remove-single-line-comments.js

Issue: https://github.com/gsoft-inc/sg-orbit/issues/217 https://github.com/gsoft-inc/sg-orbit/issues/220
- Added missing exports to react-components
- Added a Jest test to ensure we don't forget further exports

Fix react components exports

---

packages/react-components/components/icons/src/factories.js
packages/react-components/components/icons/tests/jest/factories.test.jsx
packages/react-components/package.json
packages/react-components/tests/dependencies.test.js
packages/react-components/tests/exports.test.js

Issue: https://github.com/gsoft-inc/sg-orbit/issues/229
- Added missing dependencies
- Added a Jest tests to ensure all dependencies are declared in the package.json file
- Added an exception in the icon factory for `cloneElement`
- Added a Jest test for the exception

Fix missing dependencies in last release

---

packages/react-components/components/multi-select/src/multi-select-dropdown-menu.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.variables

Issue: https://github.com/gsoft-inc/sg-orbit/issues/232

Fix horizontal alignment of multi-select items

---

packages/react-components/components/date-picker/src/date-picker-textbox-input.jsx
packages/react-components/components/date-picker/src/single/inline-single-date-picker-input.jsx
packages/react-components/components/date-picker/src/single/inline-single-date-picker.jsx
packages/react-components/components/date-picker/stories/date-range-picker/date-range-picker.stories.mdx
packages/react-components/components/date-picker/stories/single-date-picker/single-date-picker.stories.mdx
packages/react-components/components/date-picker/tests/chromatic/date-range-picker.chroma.jsx
packages/react-components/components/date-picker/tests/chromatic/single-date-picker.chroma.jsx
packages/react-components/components/dropdown/src/dropdown.jsx
packages/react-components/components/dropdown/stories/inline.stories.mdx
packages/react-components/components/dropdown/stories/searchable.stories.mdx
packages/react-components/components/dropdown/stories/standard.stories.mdx
packages/react-components/components/dropdown/tests/chromatic/item.chroma.jsx
packages/react-components/components/dropdown/tests/chromatic/searchable.chroma.jsx
packages/react-components/components/dropdown/tests/chromatic/standard.chroma.jsx
packages/react-components/components/dropdown/tests/jest/dropdown.test.js
packages/react-components/components/icons/src/sizes.js
packages/react-components/components/input/stories/input/input.stories.mdx
packages/react-components/components/multi-select/tests/chromatic/multi-select.chroma.jsx
packages/react-components/components/popup/src/popup.jsx
packages/react-components/components/search-input/src/search-input-controller.jsx
packages/react-components/components/search-input/stories/remote-search-input/remote-search-input.stories.mdx
packages/react-components/components/search-input/stories/search-input/search-input.stories.mdx
packages/react-components/components/search-input/tests/chromatic/search-input-controller.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.overrides
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.variables

Issue: https://github.com/gsoft-inc/sg-orbit/issues/203
- Allow support for an icon before the dropdown content
- Fix searchable dropdown input alignment
- Fix searchable dropdown autofocus
- Added Jest tests for searchable dropdown autofocus
- DatePicker & SearchInput containers are now `inline-block` when not fluid and are `width: 100%` when fluid
- `getIconSizeForControl` now default to MEDIUM

Add icon support to dropdown component

---

packages/icons/stories/icons.stories.mdx
packages/react-components/components/dropdown/src/dropdown.jsx
packages/react-components/components/dropdown/stories/inline.stories.mdx
packages/react-components/components/dropdown/stories/standard.stories.mdx
packages/react-components/components/dropdown/tests/chromatic/inline.chroma.jsx
packages/react-components/components/input/src/input.jsx
packages/react-components/components/input/src/textarea.jsx
packages/react-components/components/label/src/label.jsx
packages/react-components/components/multi-select/src/multi-select.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.overrides

Issue: https://github.com/gsoft-inc/sg-orbit/issues/243
- Inline dropdown now scale with text
- Inline dropdown now support having an icon before it's content

Fix inline dropdown scaling and icon support

---

packages/react-components/components/button/tests/chromatic/button/button.chroma.jsx
packages/react-components/components/date-picker/tests/chromatic/date-range-picker.chroma.jsx
packages/react-components/components/date-picker/tests/chromatic/single-date-picker.chroma.jsx
packages/react-components/components/input/tests/chromatic/input.chroma.jsx
packages/react-components/components/input/tests/chromatic/textarea.chroma.jsx
packages/react-components/components/search-input/tests/chromatic/search-input-controller.chroma.jsx
packages/react-components/components/select/tests/chromatic/inline.chroma.jsx
packages/react-components/components/select/tests/chromatic/item.chroma.jsx
packages/react-components/components/select/tests/chromatic/multiple.chroma.jsx
packages/react-components/components/select/tests/chromatic/searchable.chroma.jsx
packages/react-components/components/select/tests/chromatic/standard.chroma.jsx
storybook/stories/semantic-ui/theme/loader.chroma.jsx
storybook/stories/semantic-ui/theme/message.chroma.jsx
storybook/stories/semantic-ui/theme/placeholder.chroma.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/176

Rework input chromatic tests

---

packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/checkbox.overrides

Hotfix
Issue:
Fixed no text radio selected state.

radio no text size

---

packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/checkbox.overrides

without text with icon fix

---

packages/react-components/src/button/src/button.jsx
packages/react-components/src/button/stories/button.stories.mdx
packages/react-components/src/button/tests/chromatic/button/button.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/button.overrides
packages/tachyons/src/core/index.css

Issue: https://github.com/gsoft-inc/sg-orbit/issues/239

Added a link variant to the button component

---

.vscode/extensions.json
build/babel.config.js
jest/jest.config.js
package.json
packages/bundles/react/package.json
packages/react-components/README.md
packages/react-components/package.json
packages/react-components/src/button/src/button.jsx
packages/react-components/src/date-picker/src/date-picker-buttons.jsx
packages/react-components/src/date-picker/src/date-picker-calendar.css
packages/react-components/src/date-picker/src/date-picker-calendar.jsx
packages/react-components/src/date-picker/src/range/date-range-picker-presets.css
packages/react-components/src/date-picker/src/range/date-range-picker-presets.jsx
packages/semantic-ui-theme/semantic/src/definitions/elements/button.less
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/button.overrides
packages/tachyons/src/core/_margins.css
packages/tachyons/src/core/_paddings.css
storybook/stories/getting-started/tachyons/tachyons.stories.mdx
storybook/stories/materials/spacing/stories/spacing.stories.mdx
yarn.lock

Issue: https://github.com/gsoft-inc/sg-orbit/issues/146 https://github.com/gsoft-inc/sg-orbit/issues/23
Replaced styled-jsx by CSS stylesheets

Remove styled jsx

---

packages/react-components/package.json
packages/react-components/src/multi-select/src/multi-select-selected-items.jsx
storybook/blocks/props/props.jsx

Removed dependency to classnames

---

packages/react-components/src/input/tests/chromatic/input.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.overrides
yarn.lock

Issue:
Some minor issues related to input drop-down.
Fixed some CSS.

dropdown css fixes

---

packages/react-components/src/button/tests/chromatic/button/button.chroma.jsx
packages/react-components/src/checkbox/src/checkbox.jsx
packages/react-components/src/checkbox/stories/checkbox.stories.mdx
packages/react-components/src/checkbox/tests/chromatic/checkbox.chroma.jsx
packages/react-components/src/checkbox/tests/chromatic/shared-stories.jsx
packages/react-components/src/count/index.js
packages/react-components/src/count/src/count.css
packages/react-components/src/count/src/count.jsx
packages/react-components/src/count/src/factories.js
packages/react-components/src/count/src/index.js
packages/react-components/src/count/stories/count.stories.mdx
packages/react-components/src/count/stories/imports.mdx
packages/react-components/src/count/tests/chromatic/count.chroma.jsx
packages/react-components/src/count/tests/jest/count.test.jsx
packages/react-components/src/date-picker/src/date-picker-calendar.css
packages/react-components/src/date-picker/src/date-picker-calendar.jsx
packages/react-components/src/date-picker/src/range/date-range-picker-presets.css
packages/react-components/src/date-picker/src/range/date-range-picker-presets.jsx
packages/react-components/src/index.js
packages/react-components/src/popup/src/popup.css
packages/react-components/src/popup/src/popup.jsx
yarn.lock

Issue: https://github.com/gsoft-inc/sg-orbit/issues/280
- Added a new Count component
- Added a `count` prop to the checkbox component
- Added `.o-ui` prefix to all Orbit UI custom CSS classes

Count component

---

packages/react-components/src/select/stories/inline.stories.mdx
packages/react-components/src/select/tests/chromatic/inline.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/dropdown.overrides

Issue:
https://github.com/gsoft-inc/sg-orbit/issues/323

loading inline

---

packages/react-components/src/dropdown-menu/src/item.jsx
packages/react-components/src/dropdown-menu/tests/chromatic/sub-components.chroma.jsx
packages/react-components/src/select/src/monkey-patch-semantic-dropdown.jsx
packages/react-components/src/select/src/render-avatar.js

Issue:
Removed inline prop from avatar element

removed inline prop from avatar element

---

packages/react-components/src/date-picker/src/date-picker-anchor.jsx
packages/react-components/src/date-picker/tests/jest/date-range-picker.test.jsx
packages/react-components/src/date-picker/tests/jest/inline-single-date-picker.test.jsx
packages/react-components/src/date-picker/tests/jest/single-date-picker.test.jsx
packages/react-components/src/popper/src/popper-trigger.jsx
packages/react-components/src/popper/tests/jest/popper-trigger.test.jsx
packages/react-components/src/tags-picker/src/tags-picker-dropdown-trigger.jsx
packages/react-components/src/tags-picker/tests/jest/tags-picker.test.jsx

Issue:
Fix a few date picker keyboard navigation behaviors discovered in the focus PR.

Fix date pickers keyboard nav behaviors

---

package.json
packages/react-components/src/select/src/select.jsx
packages/react-components/src/select/stories/standard.stories.mdx
packages/react-components/src/select/tests/chromatic/standard.chroma.jsx
packages/react-components/src/select/tests/chromatic/transparent.chroma.jsx

Removed select actions feature

---

packages/foundation/src/atoms/core/colors/ui.css
packages/tachyons/docs/src/colors.css
packages/tachyons/src/ui/index.css
packages/tachyons/src/ui/neutral/_background.css
packages/tachyons/src/ui/neutral/_border.css
packages/tachyons/src/ui/neutral/_fill.css
packages/tachyons/src/ui/neutral/_text.css
packages/tachyons/src/ui/neutral/index.css
storybook/stories/materials/colors/chromatic/colors.chroma.jsx
storybook/stories/materials/colors/stories/colors.stories.mdx

Issue:
There was a need for a more neutral palette.
Added a neutral palette.
Added documentation.
/?path=/story/chromatic-colors--default

Neutra color

---

packages/react-components/src/select/stories/SelectItem.stories.mdx

Introduced in #391 
Just want to make sure master is stable!

Fix multiple stories having the same name

---

packages/icons/stories/icon-gallery/details/icon-modal.jsx
packages/icons/stories/icon-gallery/details/multi-variant.jsx
packages/icons/stories/icon-gallery/preview-icon.jsx
packages/icons/stories/icons.stories.mdx
packages/react-components/src/field/tests/chromatic/Field.chroma.jsx
packages/react-components/src/field/tests/chromatic/FieldGroup.chroma.jsx
packages/react-components/src/field/tests/chromatic/FieldMessage.chroma.jsx
packages/react-components/src/field/tests/chromatic/GroupField.chroma.jsx
packages/react-components/src/field/tests/chromatic/Label.chroma.jsx
packages/react-components/src/form/tests/chromatic/Form.chroma.jsx
packages/react-components/src/icons/stories/Icon.stories.mdx
packages/react-components/src/text/src/Heading.css
packages/react-components/src/text/src/Heading.jsx
packages/react-components/src/text/src/Paragraph.css
packages/react-components/src/text/src/index.js
packages/react-components/src/text/stories/Heading.stories.mdx
packages/react-components/src/text/stories/HeadingImports.mdx
packages/react-components/src/text/stories/Paragraph.stories.mdx
packages/react-components/src/text/stories/ParagraphImports.mdx
packages/react-components/src/text/tests/chromatic/Heading.chroma.jsx
packages/react-components/src/text/tests/chromatic/Paragraph.chroma.jsx
packages/react-components/src/text/tests/chromatic/Text.chroma.jsx
packages/react-components/src/text/tests/jest/Heading.test.jsx
packages/react-components/src/text/tests/jest/Paragraph.test.jsx

Issue:
Added Heading & Paragraph components

Heading paragraph

---

packages/react-components/src/button/src/Button.css

Issue:
Some outline buttons were not looking as wanted.
Changed some classes .outline to .o-ui-button-outline

toggle button outline fix

---

packages/react-components/src/text/src/Heading.css

heading last-child

---

packages/react-components/src/alert/src/Alert.css
packages/react-components/src/alert/src/Alert.jsx

Updating Alert content container to a div

---

packages/react-components/src/alert/docs/Alert.stories.mdx
packages/react-components/src/alert/src/Alert.jsx
packages/react-components/src/alert/tests/chromatic/Alert.chroma.jsx
packages/react-components/src/shared/src/ContentStyleContext.js
packages/react-components/src/text/src/Heading.jsx
packages/react-components/src/text/stories/heading/Heading.stories.mdx
storybook/config/sort-stories.js

Issue:
- Wrote docs for Alert
- An alert dismiss button nos inherit it's font color

Added docs for Alert

---

packages/react-components/src/list/src/List.tsx

Converted List component to typescript

Feature/convert components part2 - List component

---

packages/react-components/src/index.css
storybook/preview.js

Removed the fonts when running chromatic to prevent intermitent failing

---

docs/getting-started/Installation.stories.mdx
docs/getting-started/Slots.stories.mdx
packages/bundles/react/package.json
packages/bundles/react/src/apricot.css
packages/bundles/react/src/index.css
packages/icons/docs/icon-gallery/details/Variants.css
packages/icons/docs/icon-gallery/details/Variants.jsx
packages/react-components/src/autocomplete/docs/Autocomplete.stories.mdx
packages/react-components/src/box/src/Box.tsx
packages/react-components/src/box/tests/chromatic/Box.chroma.jsx
packages/react-components/src/collection/docs/Item.stories.mdx
packages/react-components/src/collection/docs/Section.stories.mdx
packages/react-components/src/disclosure/src/Disclosure.tsx
packages/react-components/src/shared/src/forwardRef.ts
packages/react-components/src/theme-provider/docs/ColorSchemePicker.sample.jsx
packages/react-components/src/theme-provider/docs/ThemeProvider.stories.mdx
packages/react-components/src/theme-provider/src/ThemeProvider.tsx
storybook/preview.js

Docs improvement

---

build/babel.config.js
package.json
packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/collection/src/useCollectionSearch.ts
packages/react-components/src/listbox/src/Listbox.tsx
packages/react-components/src/listbox/src/ListboxOption.tsx
packages/react-components/src/menu/docs/Selection.sample.jsx
packages/react-components/src/menu/src/Menu.tsx
packages/react-components/src/number-input/src/NumberInput.css
packages/react-components/src/select/src/Select.tsx
packages/react-components/src/shared/src/mergeProps.ts
packages/react-components/src/shared/src/omitProps.ts
yarn.lock

Minor fixes

---

packages/react-components/src/form/docs/Form.stories.mdx
packages/react-components/src/tag/docs/Tag.stories.mdx
packages/react-components/src/tag/docs/TagsPicker.sample.jsx

Fix Tags code sample to replace items by an array map

---

CONTRIBUTING.md
docs/getting-started/Installation.stories.mdx
docs/getting-started/Slots.stories.mdx
docs/getting-started/Tachyons.stories.mdx
docs/getting-started/foundation/Foundation.stories.mdx
docs/materials/colors/Colors.stories.mdx
packages/foundation/src/colors.css
packages/icons/docs/icons.stories.mdx
packages/react-components/src/input/src/Input.css
packages/react-components/src/overlay/src/Overlay.tsx
packages/react-components/src/tabs/docs/Tabs.stories.mdx
packages/react-components/src/tag/docs/Tag.stories.mdx
yarn.lock

Doc validation

---

packages/react-components/src/link/src/TextLink.tsx

For issue https://github.com/gsoft-inc/sg-orbit/issues/539

Retyped TextLink's children

---

packages/react-components/src/tabs/src/Tabs.tsx

Change tab properties from required to optional

---

packages/react-components/src/alert/src/Alert.tsx
packages/react-components/src/checkbox/src/Checkbox.tsx
packages/react-components/src/checkbox/src/CheckboxGroup.tsx
packages/react-components/src/field/src/Label.tsx
packages/react-components/src/icons/src/IconList.tsx
packages/react-components/src/list/src/List.tsx
packages/react-components/src/menu/src/MenuItem.tsx
packages/react-components/src/menu/src/MenuTrigger.tsx
packages/react-components/src/radio/src/RadioGroup.tsx
packages/react-components/src/transition/src/Transition.tsx
packages/react-components/src/visually-hidden/src/VisuallyHidden.tsx

Export all component props

---

packages/react-components/src/button/src/ButtonGroup.tsx
packages/react-components/src/button/src/IconButton.tsx
packages/react-components/src/button/src/ToggleIconButton.tsx
packages/react-components/src/divider/src/Divider.tsx
packages/react-components/src/dot/src/Dot.tsx
packages/react-components/src/lozenge/src/Lozenge.tsx

All children should use ReactNode instead of ReactElement

---

packages/react-components/src/alert/src/Alert.css

Issue: https://github.com/gsoft-inc/sg-orbit/issues/610
This PR fixes issue above.

fixed issue where icon was shrinking

---

packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/button/src/ToggleButton.tsx
packages/react-components/src/button/src/ToggleIconButton.tsx
packages/react-components/src/button/src/useToggleButton.ts
packages/react-components/src/checkbox/src/Checkbox.tsx
packages/react-components/src/checkbox/src/useCheckbox.ts
packages/react-components/src/date-input/src/DateInput.tsx
packages/react-components/src/date-input/src/useDateInput.ts
packages/react-components/src/overlay/src/usePopup.ts
packages/react-components/src/popover/src/PopoverTrigger.tsx
packages/react-components/src/select/src/Select.tsx
packages/react-components/src/select/src/useSelect.ts
packages/react-components/src/switch/src/Switch.tsx

auto controlled properties in hook now accept nulls

---

packages/react-components/src/autocomplete/docs/RemoteItems.sample.jsx
packages/react-components/src/listbox/docs/Listbox.stories.mdx
packages/react-components/src/listbox/src/Listbox.css
packages/react-components/src/listbox/src/Listbox.tsx
packages/react-components/src/listbox/tests/chromatic/Listbox.chroma.jsx
packages/react-components/src/menu/docs/Menu.stories.mdx
packages/react-components/src/menu/src/Menu.css
packages/react-components/src/menu/src/Menu.tsx
packages/react-components/src/menu/tests/chromatic/Menu.chroma.jsx
packages/react-components/src/select/docs/Select.stories.mdx
packages/react-components/src/select/src/Select.tsx
packages/react-components/src/select/src/useSelect.ts
packages/react-components/src/select/tests/chromatic/createTestSuite.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/618
- Added a validationState to Listbox & Menu
- Select pass is validationState down to Listbox
- Menu item focus style have been updated to match Listbox option focus style (a selection bar have been added)

Added a validationState prop to Listbox & Menu

---

packages/react-components/package.json
packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/date-input/src/DateRangeInput.tsx
packages/react-components/src/dialog/src/Modal.tsx
packages/react-components/src/menu/src/MenuTrigger.tsx
packages/react-components/src/overlay/src/isTargetParent.ts
packages/react-components/src/overlay/src/useInteractOutside.ts
packages/react-components/src/overlay/src/useOverlayPosition.ts
packages/react-components/src/overlay/src/usePopup.ts
packages/react-components/src/overlay/src/usePopupLightDismiss.ts
packages/react-components/src/overlay/src/useTriggerWidth.ts
packages/react-components/src/select/src/useSelect.ts
packages/react-components/src/shared/src/useAutoFocus.ts
packages/react-components/src/shared/src/useMergedRefs.ts
packages/react-components/src/shared/src/useResizeObserver.ts
packages/react-components/src/tooltip/src/TooltipTrigger.tsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/514
- Replaced usePopper by a custom implementation using popperjs core
- Updated all hooks to use refs instead of elements

Updated all hooks to accept refs instead of elements

---

packages/react-components/src/alert/src/Alert.tsx
packages/react-components/src/field/src/FieldMessage.tsx
packages/react-components/src/paragraph/src/Paragraph.tsx

replaced dotted link by underline link in paragraph

---

packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/menu/tests/jest/MenuTrigger.test.jsx
packages/react-components/src/overlay/src/useRestoreFocus.ts
packages/react-components/src/overlay/tests/jest/usePopup.test.jsx
packages/react-components/src/select/tests/jest/Select.test.jsx
packages/react-components/src/shared/src/useFocusScope.ts

- Fix useRestoreFocus by removing cleanup up code in useFocusScope. Not a really good idea I guess but it works for now.
- Added tests coverage for restore focus behavior.

Fixing restore focus

---

docs/getting-started/Installation.stories.mdx

Issue: 
#645 
Fixed font installation doc that was innacurate.

doc update

---

packages/react-components/src/autocomplete/src/Autocomplete.css
packages/react-components/src/checkbox/src/Checkbox.css
packages/react-components/src/listbox/src/Listbox.css
storybook/components/preview/Preview.css

Issue: 
#649 /  #650 / #651
Batched some issues.

Fixed #649 #650 #651

---

packages/react-components/src/tabs/src/Tab.tsx
packages/react-components/src/tabs/src/TabList.tsx
packages/react-components/src/tabs/src/Tabs.tsx
packages/react-components/src/tabs/tests/jest/Tabs.test.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/658

Fixing issue

---

packages/react-components/src/button/src/useButton.ts
packages/react-components/src/button/tests/jest/Button.test.jsx

Issue : https://github.com/gsoft-inc/sg-orbit/issues/674

fix condition so button does not always override the value of type

---

packages/react-components/src/date-input/src/useDateInput.ts
packages/react-components/src/date-input/tests/chromatic/DateInput.chroma.jsx
packages/react-components/src/date-input/tests/jest/DateInput.test.jsx
packages/react-components/src/number-input/tests/jest/NumberInput.test.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/672
- Update useDateInput date comparaison code to compare with getTime() instead of the date objects reference.

Fix onDateChange call when the date doesn't change

---

packages/react-components/src/accordion/src/useAccordionItems.ts
packages/react-components/src/accordion/tests/chromatic/Accordion.chroma.jsx
packages/react-components/src/autocomplete/tests/chromatic/Autocomplete.chroma.jsx
packages/react-components/src/collection/src/useCollection.ts
packages/react-components/src/menu/tests/chromatic/Menu.chroma.jsx
packages/react-components/src/select/tests/chromatic/Select.chroma.jsx
packages/react-components/src/tabs/src/useTabsItems.ts
packages/react-components/src/tabs/tests/chromatic/Tabs.chroma.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/680
Added support for collection item conditional rendering

Added support for collection item conditional rendering

---

packages/react-components/src/field/src/FieldMessage.tsx
packages/react-components/src/field/src/Label.tsx
packages/react-components/src/index.css
packages/react-components/src/listbox/src/ListboxOption.tsx
packages/react-components/src/menu/src/MenuItem.tsx

Issues:
#603 / #667 / #666 
Fixed a bunch of issues.
- Added a smooth scroll by default.
- Fixed typo sizes in Fields
- Fixed typo sizes in Listbox and Menu

bundle of issues

---

packages/react-components/src/avatar/src/Avatar.css
packages/react-components/src/avatar/src/AvatarGroup.tsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/690
- Updated avatar group to match the new design specs https://www.figma.com/file/VATs1Zu2vEXqIBicdwP3fI/Orbit---UIKit?node-id=7149%3A332

Added a tooltip to AvatarGroup items and remainings

---

packages/react-components/src/form/docs/Form.stories.mdx
packages/react-components/src/form/src/Fieldset.tsx
packages/react-components/src/form/src/Form.css
packages/react-components/src/form/src/index.ts
packages/react-components/src/form/tests/chromatic/Fieldset.chroma.jsx
packages/react-components/src/form/tests/chromatic/Form.chroma.jsx
packages/react-components/src/input-group/docs/InputGroup.stories.mdx
storybook/styles/docs.css

Issue: 
- Added a fieldset component to form

Added a fieldset component to form

---

packages/fonts/src/interphases/font.css

added font swap to tt interphases

---

packages/react-components/src/alert/src/Alert.tsx
packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/avatar/src/Avatar.tsx
packages/react-components/src/avatar/src/AvatarGroup.tsx
packages/react-components/src/button/src/ButtonGroup.tsx
packages/react-components/src/date-input/src/DateInput.tsx
packages/react-components/src/date-input/src/DateRangeInput.tsx
packages/react-components/src/dialog/src/Dialog.tsx
packages/react-components/src/field/src/FieldMessage.tsx
packages/react-components/src/field/src/Label.tsx
packages/react-components/src/form/src/Row.tsx
packages/react-components/src/group/src/Group.tsx
packages/react-components/src/illustration/src/Illustration.tsx
packages/react-components/src/layout/src/Flex.tsx
packages/react-components/src/layout/src/Inline.tsx
packages/react-components/src/layout/src/Stack.tsx
packages/react-components/src/listbox/src/ListboxOption.tsx
packages/react-components/src/menu/src/Menu.tsx
packages/react-components/src/menu/src/MenuItem.tsx
packages/react-components/src/modal/src/Modal.tsx
packages/react-components/src/shared/src/mergeProps.ts
packages/react-components/src/tag/src/TagList.tsx
packages/react-components/src/text-input/src/PasswordInput.tsx
packages/react-components/src/text-input/src/SearchInput.tsx
packages/react-components/src/tile/src/Tile.tsx
packages/react-components/src/tile/src/TileGroup.tsx
packages/react-components/src/toolbar/src/Toolbar.tsx

Fix mergeProps with as const

---

packages/react-components/src/autocomplete/src/Autocomplete.tsx
packages/react-components/src/collection/src/Item.tsx
packages/react-components/src/collection/src/Section.tsx
packages/react-components/src/collection/src/useAsyncSearch.ts
packages/react-components/src/listbox/src/ListboxOption.tsx
packages/react-components/src/menu/src/MenuItem.tsx
packages/react-components/src/menu/src/MenuTrigger.tsx
packages/react-components/src/radio/src/RadioGroup.tsx
packages/react-components/src/select/src/useSelect.ts
tsconfig.json

Deactivate noUnusedParameters in TSConfig

---

packages/react-components/src/link/src/useLink.ts
packages/react-components/src/link/tests/jest/TextLink.test.tsx

https://github.com/gsoft-inc/sg-orbit/issues/733

external now add target="_blank" by default

---

packages/bundles/react/package.json
packages/react-components/package.json

- @orbit-ui/react-components@18.1.1
- @orbit-ui/react@20.1.1
Issue: 

Release 2021-08-25

---

packages/components/src/listbox/src/Listbox.tsx
packages/components/src/menu/src/Menu.tsx

Follow up to #756 - Fixing #752

752 - follow up: use nodes instead of nodesProp

---

docs/materials/Shadows.stories.mdx

Fixed copy paste error in Shadow stories

---

packages/components/src/alert/src/Alert.css

#751 Alert Warning and Alert Icon does not have the right color

---

docs/getting-started/styling/StyledSystem.stories.mdx
docs/materials/typography/Typography.stories.mdx

Issue: 
While reading the typography docs I encountered a few values which were still bound to Tachyons and a broken link.
Also, I think a font-size scale is missing in the typography page, it's not obvious to find out what the underlying value a font-size scale value.
@fraincs I'll let you review, fix & merge at your convenience!

Typography docs fixes

---

packages/components/src/image/src/AsyncImage.tsx
packages/components/src/shared/src/index.ts
packages/components/src/shared/src/useCancellableEffect.tsx

#773 Potential memory leak in async image

---

packages/components/src/dialog/src/Dialog.tsx
packages/components/src/menu/docs/Menu.stories.mdx
packages/components/src/menu/docs/Modal.sample.jsx
packages/components/src/modal/docs/CustomTrigger.sample.jsx
packages/components/src/modal/docs/Modal.stories.mdx

Added docs examples for custom modal trigger.
- One in the modal docs
- One in the menu docs

Added docs examples for custom modal trigger

---

packages/components/src/dialog/src/Dialog.tsx
packages/components/src/dialog/tests/jest/Dialog.test.tsx
packages/components/src/menu/docs/Modal.sample.jsx
packages/components/src/modal/docs/CustomTrigger.sample.jsx
packages/components/src/popover/src/Popover.tsx
packages/components/src/popover/tests/jest/Popover.test.tsx

Added an onClose handler on dialog and popover

Added an onClose handler on dialog and popover

---

packages/components/src/typography/src/Heading.css

Issue: 
Headings font weights have been changed to reflect the designs.
Changed the CSS

font weight changes

---

docs/features/style-props/StyleProps.stories.mdx
packages/components/src/styling/src/StyleContext.ts

Issue: 
Added a custom components section to the style props docs

Added a custom components section to the style props docs

---

packages/components/src/select/src/Select.tsx

Issue: 
Updated Select to use a Box component for the trigger.

Updated Select to use a Box component for the trigger

---

package.json
yarn.lock

This PR Updates our current Browserslist package to its latest version (2.0.0): https://github.com/gsoft-inc/sg-browserslist/releases
This will increase the amount of supported browsers in our browserslist to `> 0.2%` au lieu de `> 1%`
Realted Issue: #864

Update browserslist package

---

packages/components/src/tabs/src/TabList.tsx
packages/components/src/tabs/src/Tabs.tsx
packages/components/src/tabs/src/TabsContext.ts
packages/components/src/tabs/tests/chromatic/Tabs.chroma.jsx
packages/components/src/tabs/tests/jest/Tabs.test.tsx

Issue: 
Try to fix inconsistent Tabs jest tests by adding a `collapsible` prop and set it to false in Jest tests.

Try to fix inconsistent Tabs jest tests

---

packages/components/src/typography/docs/Text.stories.mdx

Issue: 
Added an explanation about type scale in the text component docs

Added an explanation about type scale in the text component docs

---

packages/components/src/modal/docs/Modal.stories.mdx

Issue: 
#943 
Image was not showing in Modal image sample.
Added SpacePortraitHorizontal to the preview scope.
/?path=/docs/modal--default-story#image

image was not in scope

---

docs/features/ResponsiveStyles.stories.mdx
docs/features/color-schemes/ColorSchemes.stories.mdx
docs/features/style-props/StyleProps.stories.mdx
docs/features/theming/ThemeSpecificationTable.jsx
docs/features/theming/Theming.stories.mdx
docs/getting-started/Installation.stories.mdx

Issue: 
Grammar issues, typos as well as missing tables were present in many doc pages, this PR aims at fixing these on these pages: 
- Installation
- Platforms
FEATURES
- Style props
- Responsive styles
- Theming
- Color schemes
Reworded many phrases, removed unnecessary information, fixed an issue where a variable table was not showing.

Rewording and fix of some features doc pages

---

packages/components/src/lozenge/docs/Lozenge.stories.mdx

Issue: 
Lozenge had no best practices and accessibility sections, this PR aims at adding more information to better guide devs and designers in how to use this component.
Reworded some usage sections, added a best practices, related and accessibility section.
visit https://deploy-preview-956--sg-storybook.netlify.app/?path=/docs/lozenge--default-story

Document Lozenge Usage specs

---

packages/components/src/button/docs/Button.stories.mdx

Issue: 
Fix for issue #977. 
Added sections (Accessibility / when to use / VS  as well as content).
?path=/docs/button--default-story#toggle-button

added documentation to the button mdx

---

packages/components/src/accordion/src/Accordion.css
packages/components/src/button/src/Button.css
packages/components/src/checkbox/src/Checkbox.css
packages/components/src/date-input/src/DateRangeInput.css
packages/components/src/input/src/Input.css
packages/components/src/link/src/Link.css
packages/components/src/listbox/src/Listbox.css
packages/components/src/menu/src/Menu.css
packages/components/src/number-input/src/NumberInput.css
packages/components/src/overlay/src/Overlay.css
packages/components/src/popover/src/Popover.css
packages/components/src/select/src/Select.css
packages/components/src/tabs/src/Tabs.css
packages/components/src/tag/src/Tag.css
packages/components/src/tile/src/Tile.css
packages/icons/docs/icon-gallery/PreviewIcon.css
storybook/styles/docs.css

Issue: 
Outline none should be replaced by outline transparent for accessibility reasons #983 
Replaced all outline none for outline transparent in the components CSS.

more accessible outline

---

packages/components/src/lozenge/docs/Lozenge.stories.mdx
packages/components/src/lozenge/src/Lozenge.css
packages/components/src/lozenge/src/Lozenge.tsx
packages/components/src/lozenge/tests/chromatic/Lozenge.chroma.jsx

Issue: 
In some situations having a fluid Lozenge made sense. This PR aims at adding a fluid prop to lozenge.
Added a `fluid` prop that renders a fluid class, as well as adding doc and tests for the fluid prop.

added fluid variant and tests

---

packages/components/src/radio/src/Radio.css

Issue: 
🐛 Radio button dot is not centered in uneven DPIs (125% / 150%) #1008
Reviewed the CSS and fixed a var name issue

modified the way we center the radio bullet / fixed transition wrong var name

---

packages/components/src/lozenge/docs/Lozenge.stories.mdx

Issue: 
Lozenge caps has not been updated in docs after https://github.com/gsoft-inc/sg-orbit/pull/1005

Lozenge caps has not been updated in docs after #1005

---

docs/getting-started/Installation.stories.mdx
packages/components/src/select/src/useSelect.tsx

Something I missed in #1037
Using a fragment wasn't required.

Remove fragment & fix snippet

---

storybook/main.js

Small test to see if this fixes our Chromatic build

Fix memory usage during Chromatic build

---

docs/features/tokens/Tokens.stories.mdx

Issue: 
#1059 
Fixed a typo in doc.

fixed typo in border token names

---

storybook/package.json

add default starting port

---

docs/getting-started/Installation.stories.mdx
packages/experimental/README.md
packages/experimental/package.json
packages/experimental/src/contextual-help/docs/ContextualHelp.stories.mdx
packages/experimental/src/contextual-help/src/ContextualHelp.tsx
packages/experimental/src/contextual-help/tests/chromatic/ContextualHelp.chroma.jsx
packages/experimental/src/contextual-help/tests/jest/ContextualHelp.test.tsx
packages/experimental/tsconfig.build.json
storybook/components/experimental-message/ExperimentalMessage.jsx
tsconfig.json

- Added installation procedure for the experimental package
- Fixed the ExperimentalMessage's font size
- Added accessibility documentation and notes to ContextualHelp 
- Added props to allow customization of the tooltip and tooltipTrigger in the ContextualHelp  component
- Fixed the experimental package dependencies

Fixes to the experimental packages and ContextualHelp component

---

docs/features/tokens/Tokens.stories.mdx

Issue: 
#1092
Replaced occurences of () for a | in all token values.

replaced () for | in tokens documentation page

---

.eslintrc.js
packages/components/src/shared/tests/jest/useControllableState.test.tsx
packages/components/src/shared/tests/jest/useId.ssr.test.tsx
packages/components/src/shared/tests/jest/useSlots.test.tsx

Related to https://github.com/gsoft-inc/sg-orbit/issues/1099

Toggle testing-library/render-result-naming-convention and fix issues

---

.eslintrc.js
packages/components/src/alert/tests/jest/AlertTrigger.test.tsx
packages/components/src/autocomplete/tests/jest/Autocomplete.test.tsx
packages/components/src/avatar/tests/jest/Avatar.test.tsx
packages/components/src/date-input/tests/jest/DateInput.test.tsx
packages/components/src/date-input/tests/jest/DateRangeInput.test.tsx
packages/components/src/dialog/tests/jest/DialogTrigger.test.tsx
packages/components/src/disclosure/tests/jest/Disclosure.test.tsx
packages/components/src/field/tests/jest/Field.test.tsx
packages/components/src/field/tests/jest/GroupField.test.tsx
packages/components/src/menu/tests/jest/MenuTrigger.test.tsx
packages/components/src/overlay/tests/jest/usePopup.test.tsx
packages/components/src/popover/tests/jest/PopoverTrigger.test.tsx
packages/components/src/select/tests/jest/Select.test.tsx
packages/components/src/shared/tests/jest/useKeyedRovingFocus.test.tsx
packages/components/src/shared/tests/jest/useRovingFocus.test.tsx
packages/components/src/tabs/tests/jest/Tabs.test.tsx
packages/components/src/tooltip/tests/jest/TooltipTrigger.test.tsx
packages/components/src/transition/tests/jest/Transition.test.tsx
packages/experimental/src/contextual-help/tests/jest/ContextualHelp.test.tsx

related to https://github.com/gsoft-inc/sg-orbit/issues/1099

Toggle testing-library/prefer-find-by

---

docs/getting-started/Installation.stories.mdx
packages/components/src/overlay/src/isDevtoolsBlurEvent.ts
packages/components/src/overlay/src/isElementInViewport.ts

- Removed unused code
- Fixed minor gotchas in the installation doc

Removed unused code and fix installation doc

---

packages/components/src/button/src/Button.css

Issue: 
Disabled Button should not have pressed state #1144
Reworked the CSS to be more specific with the active pseudo selector declaration.

disabled buttons should not have an active state

---

packages/components/src/accordion/docs/Accordion.stories.mdx
packages/components/src/autocomplete/docs/Autocomplete.stories.mdx
packages/components/src/badge/docs/Badge.stories.mdx
packages/components/src/button/docs/Button.stories.mdx
packages/components/src/checkbox/docs/Checkbox.stories.mdx
packages/components/src/icons/tests/chromatic/IconList.stories.tsx
packages/components/src/link/docs/Link.stories.mdx
packages/components/src/listbox/docs/Listbox.stories.mdx
packages/components/src/menu/docs/Menu.stories.mdx
packages/components/src/radio/docs/Radio.stories.mdx
packages/components/src/select/docs/Select.stories.mdx
packages/components/src/switch/docs/Switch.stories.mdx
packages/components/src/tabs/docs/Tabs.stories.mdx
packages/components/src/tag/docs/Tag.stories.mdx
packages/components/src/tooltip/docs/Tooltip.stories.mdx
yarn.lock

End of the day and was too tired to start something new so I've decided to update the docs example icons to use the newly created placeholder icon!

Updated docs icons to use the newly created placeholder icon

---

.changeset/config.json

Changeset take 3, ignores are for packages that we want to ignore, not files.

Changeset, remove ignores from the config files

---

packages/components/scripts/ensure-success.js
packages/components/scripts/generate-icons-components.js

Ensure-success script was needed for generating icons, bringing it back
