packages/tachyons/src/core/_box-shadow.css

👋 
J'ai trouver cette petite erreur là avec l'intégration de Orbit dans Overcast
Je sais pas si c'est juste ici qu'il faut faire le fix et je sais pas si je dois rebuild des affaires.

Fix incorrect box-shadow-4 variable in tachyons core

---

packages/react-components/components/date-picker/src/date-picker-buttons.jsx

Removed role=button since type=button is explicit enough.

fixed issue where button had no type

---

storybook/addons/brand-picker/brand-picker-docs-widget.jsx

The brand picker and the actual brand can become off-sync if the brand is changed from another tab.
Modified the BrandPickerDocsWidget to react to changes from the local storage. I made sure that the brand wasn't applied on the first mount since we don't want to overwrite css variables with the values that we're already applied.

The brand picker and the actual brand can become off-sync if the brand is changed from another tab

---

storybook/config/sort-stories.js
storybook/roots.js
storybook/stories/utils/create-section.js

Storybook navigation menu now sort component and materials ascending

Storybook navigation menu now sort component and materials ascending

---

packages/react-components/components/date-picker/package.json
yarn.lock

Issue: https://github.com/gsoft-inc/sg-orbit/issues/25
- Updated the react-dates packages to 21.5.1.
- Start SB
- Pick any date picker story
- Click on the input to open the calendar
- Look for warnings from the react-dates packages in console log, you shouldn't find any.

Removed deprecation warnings from react-dates components

---

.eslintrc.js
.prettierignore
.prettierrc.js
.stylelintrc.js
.vscode/extensions.json
.vscode/settings.json
packages/css-normalize/src/normalize.css

Issue: https://github.com/gsoft-inc/sg-orbit/issues/39 https://github.com/gsoft-inc/sg-orbit/issues/36
- Removed prettier vscode plugin
- Switche stylelint vscode plugin for https://marketplace.visualstudio.com/items?itemName=hex-ci.stylelint-plus
- Fine tune styleconfig config
- Add eslint linebreak rule to enforce unix linebreak

Use stylelint autofix instead of prettier and enforce consistant linebreaks for style and js

---

packages/react-components/components/popup/src/popup.jsx

- Added a null check in the popup component before using the containerRef since it's in a setTimeout.

Fix intermittent failing Jest tests

---

storybook/package.json

Issue: https://github.com/gsoft-inc/sg-orbit/issues/119
- Removed the boolean indicating to not add the chromatic stories in the build sb script
Use the deploy link for sb website below.

Deploy chromatic stories in SB website

---

packages/semantic-ui-theme/semantic/src/themes/sharegate/modules/checkbox.overrides
storybook/stories/semantic-ui/react/checkbox/checkbox.stories.mdx
storybook/stories/semantic-ui/theme/checkbox.chroma.jsx

Issue:
https://github.com/gsoft-inc/sg-orbit/issues/161
When no label is present in a checkbox semantic adds a class of fitted. I'm taking advantage or this and remove the centering of the checkbox in this situation.
How to test : 
Visit Storybook Doc in Checkbox

css for checkbox

---

packages/react-components/components/date-picker/src/date-picker-textbox-input.jsx

##Issue:
#192 
Changed  the DatePickerTextboxInput's min-width to 300px so it's standard with the other inputs

Issue #192: Changed the DatePickerTextboxInput's min-width 

---

packages/tachyons/src/products/apricot/index.css
packages/tachyons/src/products/desktop/index.css

Issue:
Fix the typo that prevent apricot fill style from being consumed
- Go to the Chromatic test of the icon react component and apply  fill-apricot-900 instead of sunray.
- Make sure that the color change for the Apricot one.

[208] fix typ0 that prevent apricot fill style from being consumed

---

packages/react-components/components/dropdown/src/dropdown.jsx
packages/react-components/components/icons/src/factories.js
packages/react-components/components/icons/src/icon.jsx
packages/react-components/components/icons/stories/icon.stories.mdx
packages/react-components/components/icons/tests/jest/factories.test.jsx
packages/react-components/components/icons/tests/jest/icon.test.jsx
packages/react-components/components/icons/tests/jest/multi-variant-icon.test.jsx
packages/react-components/tests/exports.test.js
storybook/stories/materials/shadows/stories/shadows.stories.mdx
storybook/stories/semantic-ui/react/message/message.stories.mdx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/224
- Added `forwardRef` to `Icon.create` and `MultiVariantIcon.create`
- Rework `ensureIsKnownIconWrapper` to allow forwardRef
- Added a bunch of Jest tests
- Added SB stories to tests hoc icons ref

Support ref for hoc icons

---

packages/react-components/src/number-input/src/number-input.jsx
packages/react-components/src/number-input/stories/number-input.stories.mdx
packages/react-components/src/number-input/tests/chromatic/number-input.chroma.jsx
packages/semantic-ui-theme/semantic/src/themes/sharegate/elements/input.overrides

Issue:
[344](https://github.com/gsoft-inc/sg-orbit/issues/344)
Arrows were showing in number inputs, causing inconsistencies between browsers and 
- Removed the arrows for all browsers
- Added support for right icon and button.

support for number input icon and removal of arrows

---

packages/react-components/src/date-picker/src/monkey-patch-day-picker.jsx
packages/react-components/src/popper/src/useAutoControlledPopper.js
yarn.lock

When opening a date picker by pressing on enter on the date picker input, *sometimes* a enter key up event is also triggered on the date picker calendar previous month nav button.
It doesn't make much sense since the calendar is not event a parent of the input they are siblings. Anyway, haven't been able to find the root of the problem. Tryed to use "stopPropagation" on the trigger without success.
The actual fix is to wait 100ms before focusing the previous month nav button. Not confortable with this but haven't been able to come with something better.

Fixed date picker enter keydown ghost event

---

packages/react-components/src/select/src/SelectItem.jsx
packages/react-components/src/select/stories/SelectItem.stories.mdx

Issue:
Semantic UI's Dropdown.Item allow for bool, number and string as valid values.
When providing a number as the value for a SelectItem in Orbit, you get a PropType warning.
The workaround right now is to cast to string and parse around the SelectItem but ideally, Orbit's Select would support for bool and number values as well as string.
Modify the PropType of SelectItem to allow for bool and number to be passed.
We know Semantic UI DropdownItem support all 3 proptype values (https://react.semantic-ui.com/modules/dropdown/), so it should simply work.
I _tried_ adding a story for my bug/usecase, I'm not sure if we want to include a story for this particular usecase.

Allow bool and number as valid proptype for SelectItem value

---

storybook/stories/materials/typography/stories/typography.stories.mdx

Issue: Typography documentation is not up to date with the current values used by ShareGate's design system.
In order to avoid conflict on which should be used, as the documentation mentions in bold **"you must use the following combination of font-size, line-height and font-weight."**.
- Changed Headlines to Title to reflect the values used in Figma (ex: Title/F1)
- Updated Title and Body values to match the UI Kit
- Added Label typo
- Added `f10` value to the Type scale
- Added alias to font-weight section, as sometimes it's not always written in numerical format.
Update the Typography documentation to reflect the current values used by our designers for our titles, body and labels.
No
- Does this need an update to the …

Update typography documentation to reflect current values of ShareGate's design system

---

packages/react-components/src/heading/docs/Heading.stories.mdx
packages/react-components/src/heading/src/Heading.tsx
packages/react-components/src/heading/tests/chromatic/Heading.chroma.jsx
packages/react-components/src/icons/src/Icon.tsx
packages/react-components/src/icons/src/MultiVariantIcon.tsx
packages/react-components/src/paragraph/docs/Paragraph.stories.mdx
packages/react-components/src/paragraph/src/Paragraph.tsx
packages/react-components/src/paragraph/tests/chromatic/Paragraph.chroma.jsx

Issue:
- Added a `<P>` alias for <Paragraph>
- Added `<H1>`, `<H2>`, `<H3>`, `<H4>`, `<H5>`, `<H6>` aliases for Headings
- Icons factories now use Inner components

Added convenience aliases for Paragraph and Headings

---

packages/react-components/src/accordion/docs/Accordion.stories.mdx
packages/react-components/src/accordion/tests/chromatic/Accordion.chroma.jsx
packages/react-components/src/autocomplete/docs/Autocomplete.stories.mdx
packages/react-components/src/autocomplete/docs/RemoteItems.sample.jsx
packages/react-components/src/autocomplete/src/Autocomplete.jsx
packages/react-components/src/collection/src/useCollection.ts
packages/react-components/src/collection/src/useCollectionSearch.js
packages/react-components/src/heading/docs/Heading.stories.mdx
packages/react-components/src/heading/tests/chromatic/Heading.chroma.jsx
packages/react-components/src/menu/docs/Menu.stories.mdx
packages/react-components/src/menu/src/Menu.jsx
packages/react-components/src/menu/tests/chromatic/Menu.chroma.jsx
packages/react-components/src/select/docs/Select.stories.mdx
packages/react-components/src/select/src/Select.jsx
packages/react-components/src/select/src/useSelect.js
packages/react-components/src/tabs/docs/Tabs.stories.mdx
packages/react-components/src/tabs/tests/chromatic/Tabs.chroma.jsx

Issue:
- Removed `items` prop from Autocomplete, Menu & Select since it can be done with a simple array map. Might want to add back later if you feel we need to add some kind of caching for performance.
- Renamed "Array map" docs examples to "Dynamic items"

Remove dynamic items

---

packages/react-components/src/menu/src/Menu.css

Issue: 
According to WAI-ARIA a disabled menu item is focusable. This was not the case UI wise.
Treated focus of a disabled menu item the same as a non disabled item via CSS.
?path=/story/chromatic-menu--autofocus-first-item-when-disabled

disabled menu item is now focusable/hoverable

---

packages/react-components/src/button/docs/Button.stories.mdx
packages/react-components/src/tag/docs/Tag.stories.mdx
packages/react-components/src/tag/docs/TagsPicker.sample.jsx
packages/react-components/src/tag/src/Tag.css
packages/react-components/src/tag/src/Tag.tsx
packages/react-components/src/tag/tests/chromatic/createTagTestSuite.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/589 https://github.com/gsoft-inc/sg-orbit/issues/587
- Added an end icon to the `<Tag>` component

Add end icons to tag

---

packages/react-components/src/checkbox/docs/AllCheckedValidation.sample.jsx
packages/react-components/src/checkbox/src/Checkbox.tsx
packages/react-components/src/checkbox/tests/jest/Checkbox.test.jsx
packages/react-components/src/checkbox/tests/jest/CheckboxGroup.test.jsx
packages/react-components/src/date-input/tests/jest/DateInput.test.jsx
packages/react-components/src/date-input/tests/jest/DateRangeInput.test.jsx
packages/react-components/src/field/tests/jest/Field.test.jsx
packages/react-components/src/field/tests/jest/GroupField.test.jsx
packages/react-components/src/radio/src/Radio.tsx
packages/react-components/src/radio/tests/jest/RadioGroup.test.jsx
packages/react-components/src/switch/src/Switch.tsx
packages/react-components/src/switch/tests/jest/Switch.test.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/601 https://github.com/gsoft-inc/sg-orbit/issues/602
- Checkbox & Radio `onChange` handler is now called when they are part of a group.
- Fix CheckboxGroup validation code sample
- Improve Checkbox & Radio tests coverage

Checkbox adjustments

---

packages/react-components/src/checkbox/src/Checkbox.tsx
packages/react-components/src/checkbox/src/useCheckbox.ts
packages/react-components/src/checkbox/tests/jest/Checkbox.test.jsx
packages/react-components/src/checkbox/tests/jest/CheckboxGroup.test.jsx
packages/react-components/src/date-input/src/DateInput.tsx
packages/react-components/src/date-input/src/DateRangeInput.tsx
packages/react-components/src/date-input/src/useDateInput.ts
packages/react-components/src/date-input/tests/jest/DateInput.test.jsx
packages/react-components/src/date-input/tests/jest/DateRangeInput.test.jsx
packages/react-components/src/input/src/useInput.ts
packages/react-components/src/number-input/src/NumberInput.tsx
packages/react-components/src/number-input/tests/chromatic/NumberInput.chroma.jsx
packages/react-components/src/number-input/tests/jest/NumberInput.test.jsx
packages/react-components/src/radio/src/Radio.tsx
packages/react-components/src/radio/tests/jest/Radio.test.jsx
packages/react-components/src/radio/tests/jest/RadioGroup.test.jsx
packages/react-components/src/switch/src/Switch.tsx
packages/react-components/src/switch/tests/jest/Switch.test.jsx
packages/react-components/src/text-area/src/TextArea.tsx
packages/react-components/src/text-area/tests/jest/TextArea.test.jsx
packages/react-components/src/text-input/src/TextInput.tsx
packages/react-components/src/text-input/tests/jest/TextInput.test.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/580
- Added an extra arg for the input value to the onChange callback of every input components
- Normalize NumberInput clamp behavior to match the DateInput clamp behavior.
- Improve NumberInput test coverage

Added an extra arg for the input value to the onChange callback of every input components

---

packages/react-components/src/link/src/Link.css
packages/react-components/src/link/src/TextLink.tsx
packages/react-components/src/link/src/useLink.ts
packages/react-components/src/link/tests/chromatic/createTextLinkTestSuite.jsx

Issue: 
This PR fixes the issue https://github.com/gsoft-inc/sg-orbit/issues/599
TextLinks were not accessible since there was no way to tell a link was a link visually before hovering it.
the underline prop now defaults to solid, none is now an accepted value for the underline prop. 
/?path=/story/chromatic-textlink--default

underline solid is now the default behaviour of a TextLink

---

packages/react-components/src/autocomplete/src/Autocomplete.css
packages/react-components/src/link/src/Link.css
storybook/styles/docs.css

Issue: 
#640 
TextLink focus states were not following the logic of other components focus states. This PR aims to fix that.
Added an outline to Textlinks instead of a background.
/?path=/docs/link--color then focus on a link using `Tab`

outline is now the focus state of links

---

packages/react-components/src/avatar/src/Avatar.tsx
packages/react-components/src/avatar/tests/chromatic/Avatar.chroma.jsx
packages/react-components/src/avatar/tests/jest/Avatar.test.jsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/694
- aria-label is now forwarded to the initials element instead of being rendered on the outer contained
- a custom aria-label prop will superceed the name prop
- the size is now properly forwarded to the initials component when used as a fallback to a failing remote image src

Fix avatar initials issues

---

packages/react-components/src/image/src/Image.tsx

Issue: https://github.com/gsoft-inc/sg-orbit/issues/697
- Image component `src` prop is now optionnal
- Added `srcSet` prop to the Image component docs

Updated image component api to have an optionnal src or srcset

---

packages/react-components/src/alert/docs/Alert.stories.mdx
packages/react-components/src/dialog/src/Dialog.tsx
packages/react-components/src/dialog/tests/jest/Dialog.test.jsx

Issue: 
The goal of this PR is to add a short blurb about the Accessibility implications of the Alert component in Orbit.
- Added documentations around the `alertdialog` role
- Added the logic to support `aria-describedby` in Dialog
- Added tests to cover the added logic.
Added documentation:
Case with only Content:
Case with `aria-describedby` configured:

Add Accessibility blurb to Alert Story in Storybook

---

packages/react-components/src/shared/src/useId.ts

https://github.com/gsoft-inc/sg-orbit/issues/715
Modified the type of the userId provided to the useId function so it properly accepts the undefined value

function useId should have an optional userId 

---

packages/components/src/collection/src/useScrollableCollection.ts
packages/components/src/listbox/src/Listbox.tsx
packages/components/src/menu/src/Menu.tsx

Issue: #752 
Autocomplete leaves an empty space or adds a scrollbar depending on the content entered.
Adding the number of results returned by the autocomplete (as node) as a dependency of useLayoutEffect for useScrollableCollection makes sure we update the size of the content of the autocomplete Listbox.

Fix Autocomplete spacing glitch

---

packages/components/src/overlay/src/Overlay.css

Issue: 
Elements with a position and z-index were displayed over the overlay from Dialogs
Adding a position to the Overlay makes sure it goes on top of the other elements

Fix Overlay not overlapping positionned elements

---

packages/components/src/number-input/src/NumberInput.tsx

Issue: #761 
When clicking on the arrows of the NumberInput in Chrome or Edge, the focus is highjacking the active state (as we force it into the input).
Moving the focus logic on the event of the value changing fixes the issue, but I'm wondering if it's opening the door to unwanted focus...

Move the focus to the value changing instead of click on the arrows

---

packages/components/src/tabs/docs/loader.css
storybook/styles/docs.css

Issue: 
The loader in the Async Tabs example wasn't showing, as reported in #783 
Fixed the colour name used from `--o-ui-alias-low-break` to `--o-ui-b-alias-low-break`.

Bug: AsyncTabs loader not showing

---

docs/getting-started/styling/PropsReference.stories.mdx
docs/getting-started/styling/PropsReferenceTable.jsx
docs/getting-started/styling/StyledSystem.stories.mdx
docs/getting-started/styling/ThemeSpecificationTable.jsx
docs/materials/Shadows.stories.mdx
packages/components/src/button/src/Button.css
packages/components/src/checkbox/src/Checkbox.css
packages/components/src/checkbox/src/Checkbox.tsx
packages/components/src/input-group/src/InputGroup.css
packages/components/src/layout/docs/Grid.stories.mdx
packages/components/src/styling/tests/chromatic/useStyledSystem.chroma.jsx
packages/components/src/tag/src/Tag.css
storybook/preview.js

Issue: 
#791 / #792 
Every components using box-shadow for a fake border reverted back to using a border instead.
Remove the ThemeSwitcher in the Doc. If we ever have two themes it'll be easy to have it back.
- #791 : /?path=/docs/button--default-story#icon /?path=/docs/tag--default-story /?path=/docs/checkbox--default-story
- #792 : Check in the doc top bar that the theme picker is gone

box shadow artifacts fix - removed theme in doc

---

packages/components/src/icons/src/Icon.tsx
packages/components/src/radio/src/Radio.tsx
packages/components/src/radio/src/RadioGroup.tsx
packages/components/src/radio/tests/chromatic/Radio.chroma.jsx
packages/components/src/radio/tests/chromatic/RadioGroup.chroma.jsx
packages/components/src/radio/tests/jest/RadioGroup.test.tsx

Issue:  https://github.com/gsoft-inc/sg-orbit/issues/826
RadioGroup onChange handler is now called when switching the value with keyboard arrows

RadioGroup onChange handler is now called when switching the value with keyboard arrows

---

docs/getting-started/Slots.stories.mdx
jest/utils/renderWithTheme.tsx
packages/components/src/radio/tests/chromatic/RadioGroup.chroma.jsx
packages/components/src/styling/docs/theme-provider/ColorSchemePicker.sample.jsx
packages/components/src/styling/docs/theme-provider/CustomColorHook.sample.jsx
packages/components/src/styling/docs/theme-provider/ThemeProvider.stories.mdx
packages/components/src/styling/src/index.ts
packages/components/src/styling/src/theming/orbitTheme.ts
packages/components/src/styling/src/useColorValue.ts
packages/components/src/styling/tests/jest/useColorValue.test.ts

Issue: https://github.com/gsoft-inc/sg-orbit/issues/807
- Fix ThemeProvider docs. All examples were using a primary variant. A primary button use the same colors for light & dark which were preventing from showing any theme feature.
- Added a `useColorValue` hook to allow a dev to easily use a custom color with color scheme support.

Fix theme provider docs and added a useColorValue hook

---

packages/components/src/dialog/src/Dialog.tsx
packages/components/src/overlay/src/index.ts
packages/components/src/overlay/src/isElementInViewport.ts
packages/components/src/overlay/src/useInteractOutside.ts
packages/components/src/overlay/src/useRestoreFocus.ts
packages/components/src/overlay/src/useTrapFocus.ts

- Clicking the trigger of an opened popover wasn't closing the popover anymore
- Updated useRestoreFocus to prevent restoring the focus an element which is not visible in the current viewport. For example, opening a popover at the top of a page, scrolling to the bottom of the page then mouse clicking anywhere to close the popover was scrolling back at the top of the page.

Fix popover closing when clicking on the trigger

---

CONTRIBUTING.md
packages/components/src/menu/src/MenuTrigger.tsx
packages/components/src/select/src/useSelect.ts
packages/components/src/shared/src/useFocusScope.ts
packages/components/src/shared/tests/jest/useFocusScope.test.tsx
packages/components/src/tabs/docs/Tabs.stories.mdx
packages/components/src/tabs/src/TabList.tsx
packages/components/src/tabs/src/useCollapsibleTabs.ts

Issue: https://github.com/gsoft-inc/sg-orbit/issues/846
Since a selected collapsed tab is promoted to visible tabs the limit must be re-computed when the selectedKey change because the newly selected tab could be larger than the available space.

Fixed collapsing tab selection can overflow tab list

---

docs/materials/colors/Colors.stories.mdx
packages/components/src/accordion/src/Accordion.css
packages/components/src/button/src/ButtonGroup.css
packages/components/src/button/src/ButtonGroup.tsx
packages/components/src/card/src/Card.css
packages/components/src/dialog/src/Dialog.css
packages/components/src/message/src/Message.css
packages/components/src/message/src/Message.tsx

Issue: 
#823 - Button content should not wrap in messages
#838 - Doc: background colours are missing Alias
#856 - ButtonGroup should wrap on multiple lines before breaking text
#861 - Message close button overflow outside it's container when it's too small

#823 / #838 / #856 / #861

---

packages/components/src/badge/src/Badge.tsx
packages/components/src/badge/tests/chromatic/Badge.chroma.jsx

Part of https://github.com/gsoft-inc/sg-orbit/issues/862 (this is the 3))
Badge style props were not forwarded to the badge but were instead rendered on the wrapper element.
- Forward style props to the badge
- Added a `wrapperProps` to allow a user to set props on the wrapper element

Fix badge component style props forward

---

packages/components/src/menu/src/Menu.css

Issue: 
Menu label letters with a descender were cut off due to an aggressive line height.
Reverted the line-height of a menu item label to `2`.

menu label lineheight fix

---

packages/components/src/button/src/TextButton.css
packages/components/src/button/tests/chromatic/createButtonTestSuite.jsx

Issue: 
#924 
Text in a fluid button was not exactly centered when a start or end-icon was present.
When a fluid button has a start icon we are offsetting it's margin-left negatively to compensate the space taken by the icon.
When a fluid button has an end icon we are offsetting it's margin-left negatively to compensate the space taken by the icon.
/?path=/story/chromatic-button-negative--icon

fluid button w/ icon margin negative fix / chromatic tests adjustments

---

packages/components/src/input/src/adaptInputStylingProps.ts

Issue: 
When passing a backgroundColor style prop the input was receiving the value, not the wrapper this PR aims at fixing this problematic.
Added backgroundColor to adaptInputStylingProps.

added background color to input wrapper

---

packages/components/src/lozenge/docs/Lozenge.stories.mdx
packages/components/src/lozenge/src/Lozenge.css
packages/components/src/lozenge/tests/chromatic/Lozenge.chroma.jsx

Issue: 
Lozenge was the only component enforcing all caps on it's text, this did not feel right as in some cases long words were hard to read in all caps, all caps being harder to read. This PR aims at let the consumer capitalize words if needed either via a style prop or by typing in all caps.
- Reworked the CSS to remove the text-transform
- Reworked the CSS to inherit a text-transform when set on the lozenge container.
- Upped the font-weight to help readability on lower end screens.
/?path=/docs/chromatic-lozenge--default

removed text transform on lozenge / added a test for text transform on a lozenge

---

packages/components/src/modal/docs/Modal.stories.mdx

Issue: 
With the dot restructure some content was still visible while now redundant. Modal still had a When to use section. 
Removed the When to use section from the Modal doc.

removed related components from Modal doc as it was redundant

---

packages/components/src/switch/docs/Switch.stories.mdx

Issue: 
Switch documentation was missing the Guidelines title.
Added the missing the Guidelines title.

added guidelines title to Switch documentation

---

packages/components/README.md
packages/components/src/accordion/docs/Accordion.stories.mdx
packages/components/src/alert/docs/Alert.stories.mdx
packages/components/src/autocomplete/docs/Autocomplete.stories.mdx
packages/components/src/button/docs/Button.stories.mdx
packages/components/src/button/docs/CrossButton.stories.mdx
packages/components/src/checkbox/docs/Checkbox.stories.mdx
packages/components/src/disclosure/docs/Disclosure.stories.mdx
packages/components/src/link/docs/Link.stories.mdx
packages/components/src/listbox/docs/Listbox.stories.mdx
packages/components/src/menu/docs/Menu.stories.mdx
packages/components/src/message/docs/Message.stories.mdx
packages/components/src/modal/docs/Modal.stories.mdx
packages/components/src/radio/docs/Radio.stories.mdx
packages/components/src/select/docs/Select.stories.mdx
packages/components/src/switch/docs/Switch.stories.mdx
packages/components/src/tabs/docs/Tabs.stories.mdx
packages/components/src/toolbar/docs/Toolbar.stories.mdx
packages/components/src/tooltip/docs/Tooltip.stories.mdx
storybook/components/component-info/ComponentInfo.jsx

Issue: 
WAI-ARIA Authoring Practices have been moved. This was impacting our doc as we link to some of their pages.
Replaced the URLs in our mdx files.
Click on the different wai-aria links in our components documentation.

swapped aria links to the moved ones

---

packages/components/src/avatar/src/Avatar.css

Issue: 
https://github.com/gsoft-inc/sg-orbit/issues/990
When a remaining Avatar had an image the name was misaligned.
Remaining list is now using flex and aligns items vertically.
?path=/docs/avatar--default-story
Create an AvatarGroup like the following, see that the on over bubble shows different alignments :
```
<AvatarGroup>
<Avatar name="Sally Ride" />
<Avatar name="Alan Shepard" />
<Avatar src={ChrisHadfield} name="Chris Hadfield" />
<Avatar name="1234" />
<Avatar src={ChrisHadfield} name="adfasdf" />
<Avatar name="AAAAA CCCCCC" />
<Avatar src={ChrisHadfield} name="asdfasdfasdfasdf" />
</AvatarGroup>
```

aligned text to avatar

---

packages/components/src/avatar/src/Avatar.css

Issue: 
While removing the avatar fix to branch feature/993 as it was not meant to be there, merging it into master removed the avatar css fixes. This PR aims at bringing the css fixes back to master.
Added the CSS that was done in https://github.com/gsoft-inc/sg-orbit/pull/991 and lost in a reconciliation.

fix reconciliate error who removed avatar css fix

---

packages/components/src/lozenge/src/Lozenge.css
packages/components/src/lozenge/src/Lozenge.tsx

Issue: 
#979 - Small Lozenge should not use lowercase text as it's hard to read.
A small Lozenge should not use lowercase text as it makes it hard to read for the users. We now enforce an uppercase on small lozenge text.
When lozenge component size is small we set the textTransform property to `uppercase` by default.

offloaded text transform to CSS

---

packages/components/src/text-area/src/TextArea.css

Issue: 
#1019 - TextArea's text doesn't have the right color in dark mode
Textarea now inherits the input text color, since the hiearchy is different from the text input where an input has it's style directly applied, a textarea has a wrapper.

textarea now inherit input color

---

packages/components/src/index.css

Issue: Fix CSS @import declaration ordering
According to [the specs](https://drafts.csswg.org/css-cascade-5/#at-import
): 
> Any `@import` rules must precede all other valid at-rules and style rules in a style sheet (ignoring `@charset` and `@layer` statement rules)
The `components/src/index.css` file didn't follow this rule.
While most build tools are able to "do what the developer expects", it's still invalid code, and some tools (notably, Vite) will give out warning messages because of this.
Moved the content of `index.css` around to respect the specs.

Fix CSS @import declaration ordering

---

storybook/decorators/withBackgroundMatchingColorScheme.jsx
storybook/decorators/withDocsContainer.jsx
storybook/decorators/withThemeProvider.jsx
storybook/utils/getGlobals.js
storybook/utils/index.js

Fixes dark mode while still using the Storybook toolbar and `globals` variable.
Turns out that the `context` variable can actually refer to two different objects: 
- **StoryContext** 
- **DocsContextProps**
**DocsContextProps.globals** is deprecated, so we need to add the two lines to access globals from the **StoryContext**:
```js
const story = docsContext.storyById(docsContext.id);
const storyContext = docsContext.getStoryContext(story);
```

Fix dark mode, using Globals

---

packages/components/src/button/docs/Button.stories.mdx

A doc examples for IconButtonAsLink was missing.

Add missing icon button link docs example

---

packages/components/tests/jest/exports.test.ts

The test located in 
packages\components\tests\exports.test.ts
was not running since the jest config specifies
testMatch: **/tests/jest/*.test.ts?(x
and the test was not in a jest folder
move the file inside a jest folder

Export test was not running

---

.eslintrc.js
packages/components/src/autocomplete/tests/jest/Autocomplete.test.tsx
packages/components/src/date-input/tests/jest/DateInput.test.tsx
packages/components/src/date-input/tests/jest/DateRangeInput.test.tsx
packages/components/src/text-input/tests/jest/SearchInput.test.tsx

By using container methods like .querySelector you may lose a lot of the confidence that the user can really interact with your UI. Also, the test becomes harder to read, and it will break more frequently.
related to https://github.com/gsoft-inc/sg-orbit/issues/1099

Allow eslint rule "testing-library/no-container" to run on unit tests

---

.eslintrc.js
packages/components/src/dialog/tests/jest/DialogTrigger.test.tsx
packages/components/src/image/tests/jest/SvgImage.test.tsx
packages/components/src/overlay/tests/jest/usePopup.test.tsx
packages/components/src/popover/tests/jest/PopoverTrigger.test.tsx

The (DOM) Testing Library allows to query DOM elements using different types of queries such as get* and query*. Using get* throws an error in case the element is not found, while query* returns null instead of throwing (or empty array for queryAllBy* ones). These differences are useful in some situations:
- using getBy* queries when asserting if element is present, so if the element is not found the error thrown will offer better info than asserting with other queries which will not throw an error.
- using queryBy* queries when asserting if element is not present, so the test doesn't fail immediately when the element is not found and the assertion can be executed properly.
Related to https://github.com/gsoft-inc/sg-orbit/issues/1099

Toggle testing-library/prefer-presence-queries

---

.eslintrc.js
packages/components/src/alert/tests/jest/Alert.test.tsx
packages/components/src/autocomplete/tests/jest/Autocomplete.test.tsx
packages/components/src/image/tests/jest/SvgImage.test.tsx
packages/components/src/listbox/tests/jest/Listbox.test.tsx
packages/components/src/menu/tests/jest/Menu.test.tsx
packages/components/src/select/tests/jest/Select.test.tsx
packages/components/src/shared/tests/jest/useRawSlots.test.tsx
packages/components/src/text-input/tests/jest/SearchInput.test.tsx
packages/components/src/tooltip/tests/jest/TooltipTrigger.test.tsx

This rule aims to disallow DOM traversal using native HTML methods and properties, such as closest, lastChild and all that returns another Node element from an HTML tree.
Related to https://github.com/gsoft-inc/sg-orbit/issues/1099

Toggle testing-library/no-node-access

---

packages/components/src/tooltip/src/TooltipTrigger.tsx
packages/components/src/tooltip/src/useTooltipTriggerState.ts

Tooltips now open one at the time, never multiple at once. Also fixed an issue where mouseLeave event would not be detected anymore when hovering the overlay
The condition 
```
if (!isTargetParent((event as FocusEvent).relatedTarget, overlayRef)) {
```
really was the issue. It was intended for blur events, but was preventing mouseLeave event from firing if the mouseleave was on the overlay. 
added a check to make sure only blur event were taking into consideration for this logic

#1141 Tooltips often stay open when hovered fast

---

packages/components/src/tooltip/src/Tooltip.tsx
packages/components/src/tooltip/src/TooltipTrigger.tsx
packages/components/src/tooltip/tests/jest/TooltipTrigger.test.tsx

Fix for issue https://github.com/gsoft-inc/sg-orbit/issues/1141
Here is 3 scenario of how the tooltip works before the fix
- MouseEnter on trigger -> Tooltip shows
- MouseLeave on Trigger  -> MouseEnter on white background -> Tooltip disappear because of the event handlers on the trigger. 
- MouseEnter on trigger -> Tooltip shows
- MouseLeave on trigger ->  MouseEnter Overlay -> Trigger's Event handler ignore the mouseLeave because it's on the overlay. and that is allowed 
- MouseEnter on Tooltip -> Tooltip stays open
- MouseLeave Tooltip -> Tooltip closes because of the event handlers on the tooltip
- MouseEnter on trigger -> Tooltip shows
- MouseLeave on Trigger -> MouseEnter on Overlay -> Trigger's Event handler ignore the mouseLeave because it's on the overlay. and that is allowed 
- …

Tooltip now closes properly when hovering the overlay without hovering the tooltip

---

packages/components/src/tile/src/Tile.css

Issue: 
https://github.com/gsoft-inc/sg-orbit/issues/1169
Moved the background color to the right css declaration.
Check the Tile doc page.

removed background-color on tile checkmark when not checked

---

.github/workflows/changeset.yml
.github/workflows/chromatic.yml

- Changeset workflow was getting cancelled by the CI because of the concurrency group.
- Also removed the nightly chromatic build since the action does not support it and it doesn't seem necessary

Modified Changeset Workflow so it doesn't get cancelled

---

.changeset/config.json

At the moment, when modifying the components project, the bundle is incremented using a patch version, instead of following the same "bump severity". 
With our current setup, the bundle basically ships the components project + ~10 lines of css from the @orbit-ui/css projects. I believe one day that we might move away from having a bundle package.
Until then, I'll link the versions of the 2 packages so every time the components packages gets updated, the bundle receives the same update. The only possible side effect i see is that if we ever modify one of the 10 lines of css from the @orbit-ui/css and the components are unaffected by the changes, we'll still bump the @orbit-ui/components packages. This is something i'm ok with.

link orbit and components together so their version is synced

---

.changeset/config.json
.changeset/happy-bananas-film.md
packages/experimental/package.json

Toggling the experimental feature to prevent releases of experimental component at every orbit-ui/component  releases .
Had to fix the release version right away to not trigger unecessary changes later

Toggling experimental feature of changeset

---

.changeset/nine-elephants-deny.md
packages/components/src/tabs/src/Tabs.css

Issue: 
Tab Trigger were not inheriting our base font-family.  Tab buttons use Arial font #1196
The tab trigger now inherits the font-family.
/?path=/docs/tabs--default-story Inspect a tab trigger.

Tabs were not inheriting our base font-family

---

packages/components/src/loader/docs/Loader.stories.mdx
packages/components/src/spinner/docs/Spinner.stories.mdx

Issue: 
Loader doc had no samples for a custom delay. Spinner Over background example was not following our norm.
Fixed these.

added sample for loader and text change for spinner

---

.changeset/rare-eyes-fly.md
packages/components/src/button/src/IconButton.tsx
packages/components/src/button/tests/jest/IconButton.test.tsx

Fixes #1207  
`aria-label` was missing on the spinner when using a loading `IconButton`, which threw a console error.
I added an aria-label to the spinner.
Yes, I add a unit test to ensure the spinner has the aria-label attribute set.
No

fix: missing aria-label on loading IconButton

---

.changeset/popular-parrots-kiss.md
packages/components/src/tooltip/src/TooltipTrigger.tsx
packages/components/src/tooltip/tests/jest/TooltipTrigger.test.tsx

Closes #1141
Seems like tooltips remaining open was related to performance, as it mostly appeared in performance intensive areas like virtualized tables.
My guess was that the issue was caused by calling the `onmouseenter` and `onmouseleave` callbacks in a single render.
My guess seems to have been confirmed after simulating a slow render by adding these lines to the `TriggerTooltip` 
```js
// We simulate a render that takes a least 500ms to happen.
// This gives us enough time to trigger both onmouseenter and onmouseleave events in a single render.
const start = performance.now();
while(performance.now() - 500 < start) {};
```
After looking into the code, I noticed that we had an if-statement that looked at the current value of `isOpen` before updating the state. `isOpen` can become …

fix: Stale closure preventing tooltip from closing on mouseleave

---

.storybook/components/banner/Banner.css
.storybook/components/banner/Banner.tsx
.storybook/components/banner/index.ts
.storybook/components/index.ts
docs/getting-started/Installation.stories.mdx

Issue: 
As we have two "similar" Design System there was a need to make sure everyone uses the right Design System.
Added a banner in the installation page warning users about which DS they should use.

added banner to redirect to Orbiter when suitable
